name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3  # Ensure this is the latest version

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Ensure this is the latest version
      with:
        node-version: '20'  # Specify the latest stable Node.js version

    - name: Install dependencies (Backend)
      working-directory: ./api
      run: npm install

    - name: Install dependencies (Frontend)
      working-directory: ./frontend
      run: npm install

    - name: Run Backend Tests
      working-directory: ./api
      run: npm test

    - name: Run Frontend Tests
      working-directory: ./frontend
      run: npm test

    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        npm install -g vercel
        vercel --prod --confirm
