name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.10]  # Python 3.9 and 3.10 are more compatible

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install python3-venv
      run: sudo apt-get install python3-venv

    - name: Reinstall distutils
      run: sudo apt-get install --reinstall python3-distutils

    - name: Update system packages
      run: sudo apt-get update && sudo apt-get upgrade -y

    - name: Install setuptools and wheel
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python manage.py test
