name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.10]  # Avoid Python 3.12 for compatibility

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade system packages
      run: sudo apt-get update && sudo apt-get upgrade -y

    - name: Force reinstall distutils
      run: sudo apt-get install --reinstall python3-distutils

    - name: Clear and Recreate Virtual Environment
      run: |
        rm -rf venv
        python -m venv venv
        source venv
